-- Session Warrant 베이스라인 스키마 (요구사항 골격 — DDL 은 아직 확정 전)
--
-- 원칙 세 가지
--   1) 계보(warrant_lineage)가 원본이고 warrant 의 현재 상태는 파생이다.
--      조회 편의로 비정규화해 두되 방향을 뒤집지 않는다.
--   2) audit_event 는 일 단위 range 파티션 + BRIN. 조회는 항상 시간 범위를 강제해 프루닝이 걸리게 한다.
--   3) subject.kernel_subject_id 는 재사용 금지. 재사용하면 과거 로그의 귀속이 조용히 뒤바뀐다.

-- TODO: proto/warrant.proto 확정 후 아래를 실제 DDL 로 채운다.
--
-- subject(id, oidc_subject UNIQUE, principal, display_name,
--         kernel_subject_id INT UNIQUE, login_account)
-- subject_ssh_key(subject_id, fingerprint UNIQUE, registered_at, revoked_at)
--         -- fingerprint UNIQUE: 한 키가 두 사람에게 등록되면 바인딩이 다시 모호해진다
--
-- policy(id, kernel_policy_id INT UNIQUE, supersedes_id, name, inspect_udp BOOL, created_at)
--         -- 한 행 = 한 버전, 불변. 수정은 새 행. kernel_policy_id 재사용 금지 (rule_* 맵 키)
-- policy_exec_rule(policy_id, path)
-- policy_write_rule(policy_id, path, recursive, effect SMALLINT CHECK (effect IN (1, 2)))
--         -- effect=DENY 는 디렉터리만 허용. 0(UNSPECIFIED)은 저장 불가
-- policy_net_rule(policy_id, cidr, port, proto SMALLINT)
-- policy_read_watch(policy_id, path)
--
-- node(id, client_cert_fingerprint UNIQUE, hostname, kernel_version, bpf_lsm_enabled,
--      agent_version, attached_hooks TEXT[], current_seq_epoch, last_seen_at, booted_at)
--         -- 노드 신원은 mTLS 인증서. hostname 은 자기 신고라 UNIQUE 키로 쓰지 않는다
--
-- warrant(id, warrant_id BIGINT UNIQUE CHECK (warrant_id > 0), revision INT,
--         display_id UNIQUE, subject_id, login_account, policy_id, reason,
--         issued_at, expires_at, grace_window INTERVAL,
--         mode SMALLINT, on_expiry SMALLINT, state, revoked BOOL, break_glass BOOL,
--         signed_payload BYTEA, signature BYTEA, signing_key_id)
--         -- warrant_id = 커널 맵 키. 전용 시퀀스, 재사용 금지. 0 은 "무영장" 자리
--         -- expires_at 는 절대 시각. bpf_ktime_get_boot_ns 변환은 warrantd 가 한다
--         -- grace_until 은 저장하지 않는다 — expires_at + grace_window 파생
-- warrant_ssh_key(warrant_id, fingerprint)       -- 발급 시점 스냅샷. 서명된 봉투와 같아야 한다
-- warrant_target_host(warrant_id, hostname)
--         -- 활성 1개 불변식 (subject, hostname, login_account): 발급 서비스가 subject 행
--         -- FOR UPDATE 로 직렬화해 지킨다. 대상 호스트가 자식 테이블이라 부분 UNIQUE 로는 못 건다
--
-- warrant_lineage(id, warrant_id, type, occurred_at, actor_id, reason, basis,
--                 delta_seconds, expires_at_after)
--         -- append-only. UPDATE/DELETE 를 막는 트리거를 걸어 두는 편이 안전하다
--
-- audit_event(id, occurred_at, node_id, seq_epoch, node_seq, warrant_id BIGINT, kernel_subject_id,
--             type, verdict, mode, tag_source, origin, pid, cgroup_id, uid,
--             device_id, inode, resolved_path, argv_truncated, destination)
--         PARTITION BY RANGE (occurred_at)
--         UNIQUE (node_id, seq_epoch, node_seq, occurred_at)   -- 재전송 멱등
--         -- 파티션 테이블의 UNIQUE 는 파티션 키를 포함해야 한다(PostgreSQL 제약).
--         -- occurred_at 은 warrantd 가 bbolt 에 담아 두는 값이라 재전송에도 같으므로 멱등이 유지된다
--         -- warrant_id 는 커널 u64 (warrant.warrant_id 와 조인). 0 = 무영장
--         -- 신뢰의 근거는 (device_id, inode) 다. resolved_path 와 argv 는 참고 정보
--
-- audit_gap(id, node_id, from_at, to_at, dropped_count, cause)
--         -- 빈 구간을 숨기지 않는다
--
-- unwarranted_session(id, node_id, observed_at, login_account, ssh_key_fingerprint, source_address,
--                     cgroup_id, reason, observed_event_count)
