-- Session Warrant 베이스라인 스키마 (요구사항 골격 — DDL 은 아직 확정 전)
--
-- 원칙 세 가지
--   1) 계보(warrant_lineage)가 원본이고 warrant 의 현재 상태는 파생이다.
--      조회 편의로 비정규화해 두되 방향을 뒤집지 않는다.
--   2) audit_event 는 일 단위 range 파티션 + BRIN. 조회는 항상 시간 범위를 강제해 프루닝이 걸리게 한다.
--   3) subject.kernel_subject_id 는 재사용 금지. 재사용하면 과거 로그의 귀속이 조용히 뒤바뀐다.

-- TODO: proto/warrant.proto 확정 후 아래를 실제 DDL 로 채운다.
--
-- subject(id, oidc_subject UNIQUE, principal, display_name,
--         kernel_subject_id INT UNIQUE, login_account)
-- subject_ssh_key(subject_id, fingerprint UNIQUE, registered_at, revoked_at)
--         -- fingerprint UNIQUE: 한 키가 두 사람에게 등록되면 바인딩이 다시 모호해진다
--
-- policy(id, name, inspect_udp BOOL)
-- policy_exec_rule(policy_id, path)
-- policy_write_rule(policy_id, path, recursive, effect)     -- effect=DENY 는 디렉터리만 허용
-- policy_net_rule(policy_id, cidr, port)
-- policy_read_watch(policy_id, path)
--
-- node(id, hostname UNIQUE, kernel_version, bpf_lsm_enabled, last_seen_at, booted_at)
--
-- warrant(id, display_id UNIQUE, subject_id, policy_id, reason,
--         issued_at, expires_at, grace_until,
--         mode SMALLINT, on_expiry SMALLINT, state, revoked BOOL,
--         signed_payload BYTEA, signature BYTEA)
--         -- expires_at 는 절대 시각. bpf_ktime_get_boot_ns 변환은 warrantd 가 한다
-- warrant_target_host(warrant_id, hostname)
--
-- warrant_lineage(id, warrant_id, type, occurred_at, actor_id, reason, basis,
--                 delta_seconds, expires_at_after)
--         -- append-only. UPDATE/DELETE 를 막는 트리거를 걸어 두는 편이 안전하다
--
-- audit_event(id, occurred_at, node_id, node_seq, warrant_id, kernel_subject_id,
--             type, verdict, pid, cgroup_id, uid,
--             device_id, inode, resolved_path, argv_truncated, destination)
--         PARTITION BY RANGE (occurred_at)
--         UNIQUE (node_id, node_seq)   -- 재전송 멱등
--         -- 신뢰의 근거는 (device_id, inode) 다. resolved_path 와 argv 는 참고 정보
--
-- audit_gap(id, node_id, from_at, to_at, dropped_count, cause)
--         -- 빈 구간을 숨기지 않는다
--
-- unwarranted_session(id, node_id, observed_at, login_account, ssh_key_fingerprint, source_address,
--                     cgroup_id, reason, observed_event_count)
